server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
      - id: costumer_full
        uri: lb://businessdomain-costumer
        predicates:
        - Path=/customer/full/**
        - Method=GET
        filters:
        - name: AuthenticationFiltering
        
      - id: costumer_service
        uri: lb://businessdomain-costumer
        predicates:
        - Path=/customer/**
        
      - id: product_service
        uri: lb://businessdomain-product
        predicates:
        - Path=/product/**
        
      - id: transaction_post
        uri: lb://businessdomain-transactions
        predicates:
        - Path=/transaction/**
        - Method=POST
        filters:
        - name: AuthenticationFiltering
        
      - id: transaction_service
        uri: lb://businessdomain-transactions
        predicates:
        - Path=/transaction/**
